server:
  port: 80

feign:
  hystrix:
    enabled: true

spring:
  application:
    name: microservicecloud-consumer-dept-fegin
#客户端注册进eureka服务列表内
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: microservicecloud-consumer-dept-80
    prefer-ip-address: true     #访问路径可以显示IP地址