server:
  port: 9527

spring:
  application:
    name: microservicecloud-zuul-gateway

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true

zuul:
  # 访问前缀 / 隐藏指定服务的ip访问
  prefix: /imwj
  ignored-services: "*"
  # 路由配置：/api-a对应微服务在Eureka中的名...
  routes:
    api-a:
      path: /api-a/**
      serviceId: microservicecloud-dept

info:
  app.name: io.imwj.com
  company.name: blog.imwj.club
  build.artifactId: $project.artifactId$
  build.version: $project.version$

